### ISSUE TITLE
add @babel/runtime as a peer dependecy

### ISSUE THREAD

**Issue by nadavbahalul** [rsuite/rsuite-icons#7]
Hi!
I have a custom webpack resolver plugin (I have special `node_modules` path with special structure).
On my project I have `@rsuite/icons` as a dependency, but when I try to require it, it fails because it tries to require `@babel/runtime`, which is not a dependency / peer dependency of `@rsuite/icons` as it should be.

Can you please add it as a peer dependency ([here](https://github.com/rsuite/rsuite-icons/blob/master/package.json#L50))?
I tried to open a PR but I don't have permissions

```javascript
"peerDependencies": {
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0",
    "@babel/runtime": ">=7.12.1"
  },
``` 

Thanks!

**Comment by SevenOutman** [comment]
Hi @nadavbahalul, thanks for raising this! I'll look into our build system and see how to properly handle this.

PR is also welcome! I don't know why opening PR was prevented - it shouldn't be. @simonguo any idea?

**Comment by nadavbahalul** [comment]
> Hi @nadavbahalul, thanks for raising this! I'll look into our build system and see how to properly handle this.
> 
> PR is also welcome! I don't know why opening PR was prevented - it shouldn't be. @simonguo any idea?

thank you!
actually I think I can open a PR but I don't have permissions to create a new branch (I got "permission denied" when tried to create a new branch)

**Comment by SevenOutman** [comment]
> thank you! actually I think I can open a PR but I don't have permissions to create a new branch (I got "permission denied" when tried to create a new branch)

Glad you would like to help! :) You need to [fork this repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo), make changes in your own fork, then submit PR targeting this repo. Please refer to the GitHub docs about [Propose changes to someone else's project](https://docs.github.com/en/get-started/quickstart/fork-a-repo#propose-changes-to-someone-elses-project)
